
language: php

php:
  - '5.6'

before_script:
  - composer install --no-interaction
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - ./vendor/bin/test-reporter

notifications:
  email: "bianco@javanile.org"
